name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate-activity-graph
        uses: Ashutosh00710/github-readme-activity-graph@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight
          output: dist/activity-graph.svg

      - name: push activity-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
