name: Generate Activity Line Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/github-user-contribution-graph@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          svg_out_path: dist/activity-graph.svg
